#!/bin/bash

if [ -n "${API_URL}" ] && [ "${API_URL}" != "none" ]; then
  echo "- Setting SSH Authorized Keys API URL"
  sed -i s!http://localhost:301/user/%s/authorized_keys!${API_URL}!g /usr/bin/github-authorized-keys
fi

#echo "- Enabling SSH TCP Forwarding"
#sed -i 's!^AllowTcpForwarding.*!AllowTcpForwarding yes!' /etc/ssh/sshd_config

echo "- Enabling passing environment variables"
sed -i 's!^PermitUserEnvironment.*!PermitUserEnvironment yes!' /etc/ssh/sshd_config
echo "AcceptEnv LANG LC_* AWS_* ARM_* GIT_* DOCKER_* TF_* TERRAGRUNT_* TZ AIVEN_* TERM_*" >>/etc/ssh/sshd_config
