#!/bin/bash

# Generate keys and save on home volume to persist
if [ ! -f /home/etc/ssh/ssh_host_rsa_key ]; then
  mkdir -p /home/etc/ssh
  ssh-keygen -t rsa -f /home/etc/ssh/ssh_host_rsa_key -N ""
fi

# Copy host key from shared FS to local FS inside container to speed up SSH fork
cp -p /home/etc/ssh/ssh_host_rsa_key* /etc/ssh/
